DROP TABLE IF EXISTS ENTREPRISE;
DROP TABLE IF EXISTS EXERCICE;
DROP TABLE IF EXISTS STRUCTURE_ANALYTIQUE;
DROP TABLE IF EXISTS FEC;

CREATE TABLE ENTREPRISE
(
    ID_ENTREPRISE SERIAL primary key,
    NAME_ENTREPRISE VARCHAR(80),
    DESCRIPTION_ENTREPRISE TEXT,
    STRUCTURE_ANALYTIQUE INT
);

CREATE TABLE EXERCICE
(
    ID_EXERCICE SERIAL primary key,
    ENTREPRISE INT,
    FEC INT,
    DATE_BEGIN DATE,
    DATE_END DATE
);

CREATE TABLE STRUCTURE_ANALYTIQUE
(
    ID_STRUCTURE SERIAL primary key,
    ALIAS_STRUCTURE VARCHAR(80),
    SECTION VARCHAR(4),
    COMPTE_ANALYTIQUE TEXT,
    LIBELLE TEXT
);

CREATE TABLE FEC
(
    ID_FEC SERIAL primary key,
    FEC INT,
    JOURNAL_CODE VARCHAR(3),
    JOURNAL_LIB TEXT,
    ECRITURE_NUM INT,
    ECRITURE_DATE DATE,
    COMPTE_NUM VARCHAR(6),
    COMPTE_LIB TEXT,
    COMPTE_AUX_NUM TEXT,
    COMPTE_AUX_LIB TEXT,
    PIECE_REF VARCHAR(3),
    PIECE_DATE DATE,
    ECRITURE_LIB TEXT,
    MONTANT FLOAT,
    SENS CHAR,
    ECRITURE_LET TEXT,
    DATE_LET DATE,
    VALID_DATE DATE,
    MONTANT_DEVISE FLOAT,
    I_DEVISE TEXT
);

