package comptedit_db;
// Generated 3 juin 2014 00:48:18 by Hibernate Tools 3.6.0



/**
 * Exercice generated by hbm2java
 */
public class Exercice  implements java.io.Serializable {


     private Long idExercice;
     private Integer entreprise;
     private Integer fecId;

    public Exercice() {
    }

    public Exercice(Integer entreprise, Integer fecId) {
       this.entreprise = entreprise;
       this.fecId = fecId;
    }
   
    public Long getIdExercice() {
        return this.idExercice;
    }
    
    public void setIdExercice(Long idExercice) {
        this.idExercice = idExercice;
    }
    public Integer getEntreprise() {
        return this.entreprise;
    }
    
    public void setEntreprise(Integer entreprise) {
        this.entreprise = entreprise;
    }
    public Integer getFecId() {
        return this.fecId;
    }
    
    public void setFecId(Integer fecId) {
        this.fecId = fecId;
    }




}


