package comptedit_db;
// Generated 5 juin 2014 15:14:36 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Fec generated by hbm2java
 */
public class Fec  implements java.io.Serializable {


     private Long idFec;
     private Integer fec;
     private String journalCode;
     private String journalLib;
     private Integer ecritureNum;
     private Date ecritureDate;
     private String compteNum;
     private String compteLib;
     private String compteAuxNum;
     private String compteAuxLib;
     private String pieceRef;
     private Date pieceDate;
     private String ecritureLib;
     private Float montant;
     private Character sens;
     private String ecritureLet;
     private Date dateLet;
     private Date validDate;
     private Float montantDevise;
     private String IDevise;

    public Fec() {
    }

    public Fec(Integer fec, String journalCode, String journalLib, Integer ecritureNum, Date ecritureDate, String compteNum, String compteLib, String compteAuxNum, String compteAuxLib, String pieceRef, Date pieceDate, String ecritureLib, Float montant, Character sens, String ecritureLet, Date dateLet, Date validDate, Float montantDevise, String IDevise) {
       this.fec = fec;
       this.journalCode = journalCode;
       this.journalLib = journalLib;
       this.ecritureNum = ecritureNum;
       this.ecritureDate = ecritureDate;
       this.compteNum = compteNum;
       this.compteLib = compteLib;
       this.compteAuxNum = compteAuxNum;
       this.compteAuxLib = compteAuxLib;
       this.pieceRef = pieceRef;
       this.pieceDate = pieceDate;
       this.ecritureLib = ecritureLib;
       this.montant = montant;
       this.sens = sens;
       this.ecritureLet = ecritureLet;
       this.dateLet = dateLet;
       this.validDate = validDate;
       this.montantDevise = montantDevise;
       this.IDevise = IDevise;
    }
   
    public Long getIdFec() {
        return this.idFec;
    }
    
    public void setIdFec(Long idFec) {
        this.idFec = idFec;
    }
    public Integer getFec() {
        return this.fec;
    }
    
    public void setFec(Integer fec) {
        this.fec = fec;
    }
    public String getJournalCode() {
        return this.journalCode;
    }
    
    public void setJournalCode(String journalCode) {
        this.journalCode = journalCode;
    }
    public String getJournalLib() {
        return this.journalLib;
    }
    
    public void setJournalLib(String journalLib) {
        this.journalLib = journalLib;
    }
    public Integer getEcritureNum() {
        return this.ecritureNum;
    }
    
    public void setEcritureNum(Integer ecritureNum) {
        this.ecritureNum = ecritureNum;
    }
    public Date getEcritureDate() {
        return this.ecritureDate;
    }
    
    public void setEcritureDate(Date ecritureDate) {
        this.ecritureDate = ecritureDate;
    }
    public String getCompteNum() {
        return this.compteNum;
    }
    
    public void setCompteNum(String compteNum) {
        this.compteNum = compteNum;
    }
    public String getCompteLib() {
        return this.compteLib;
    }
    
    public void setCompteLib(String compteLib) {
        this.compteLib = compteLib;
    }
    public String getCompteAuxNum() {
        return this.compteAuxNum;
    }
    
    public void setCompteAuxNum(String compteAuxNum) {
        this.compteAuxNum = compteAuxNum;
    }
    public String getCompteAuxLib() {
        return this.compteAuxLib;
    }
    
    public void setCompteAuxLib(String compteAuxLib) {
        this.compteAuxLib = compteAuxLib;
    }
    public String getPieceRef() {
        return this.pieceRef;
    }
    
    public void setPieceRef(String pieceRef) {
        this.pieceRef = pieceRef;
    }
    public Date getPieceDate() {
        return this.pieceDate;
    }
    
    public void setPieceDate(Date pieceDate) {
        this.pieceDate = pieceDate;
    }
    public String getEcritureLib() {
        return this.ecritureLib;
    }
    
    public void setEcritureLib(String ecritureLib) {
        this.ecritureLib = ecritureLib;
    }
    public Float getMontant() {
        return this.montant;
    }
    
    public void setMontant(Float montant) {
        this.montant = montant;
    }
    public Character getSens() {
        return this.sens;
    }
    
    public void setSens(Character sens) {
        this.sens = sens;
    }
    public String getEcritureLet() {
        return this.ecritureLet;
    }
    
    public void setEcritureLet(String ecritureLet) {
        this.ecritureLet = ecritureLet;
    }
    public Date getDateLet() {
        return this.dateLet;
    }
    
    public void setDateLet(Date dateLet) {
        this.dateLet = dateLet;
    }
    public Date getValidDate() {
        return this.validDate;
    }
    
    public void setValidDate(Date validDate) {
        this.validDate = validDate;
    }
    public Float getMontantDevise() {
        return this.montantDevise;
    }
    
    public void setMontantDevise(Float montantDevise) {
        this.montantDevise = montantDevise;
    }
    public String getIDevise() {
        return this.IDevise;
    }
    
    public void setIDevise(String IDevise) {
        this.IDevise = IDevise;
    }




}


