package comptedit_db;
// Generated 5 juin 2014 15:14:36 by Hibernate Tools 3.6.0



/**
 * StructureAnalytique generated by hbm2java
 */
public class StructureAnalytique  implements java.io.Serializable {


     private Long idStructure;
     private String aliasStructure;
     private String section;
     private String compteAnalytique;
     private String libelle;

    public StructureAnalytique() {
    }

    public StructureAnalytique(String aliasStructure, String section, String compteAnalytique, String libelle) {
       this.aliasStructure = aliasStructure;
       this.section = section;
       this.compteAnalytique = compteAnalytique;
       this.libelle = libelle;
    }
   
    public Long getIdStructure() {
        return this.idStructure;
    }
    
    public void setIdStructure(Long idStructure) {
        this.idStructure = idStructure;
    }
    public String getAliasStructure() {
        return this.aliasStructure;
    }
    
    public void setAliasStructure(String aliasStructure) {
        this.aliasStructure = aliasStructure;
    }
    public String getSection() {
        return this.section;
    }
    
    public void setSection(String section) {
        this.section = section;
    }
    public String getCompteAnalytique() {
        return this.compteAnalytique;
    }
    
    public void setCompteAnalytique(String compteAnalytique) {
        this.compteAnalytique = compteAnalytique;
    }
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }




}


