/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Models.List.ListExercice;
import Models.List.ListSelectionListenerEntreprise;
import Models.Table.TableEntreprise;
import Renderer.List.ListRenderer;
import Renderer.Table.TableEntepriseRenderer;
import Tools.Resizer;
import comptedit_db.Entreprise;
import comptedit_db.EntrepriseRequest;
import comptedit_db.Exercice;
import comptedit_db.ExerciceRequest;
import java.awt.BorderLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.ListSelectionModel;
import javax.swing.SwingUtilities;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Flash
 */
public class Desktop_view extends javax.swing.JFrame {

    /**
     * Creates new form Desktop_view
     */
    public Desktop_view() {
        this.setIconImage(Resizer.get_resize_icon("Icon/stat.png", 100, 100).getImage());
        initComponents();
          
        
        em_ = new TableEntreprise(jTable1);
        em_.setSearch(jXSearchField1);
        
        jTable1.setModel(em_);

        EntrepriseRequest.getInstance().add_fire_component(em_, jTable1);
        

        le_ = new ListExercice(jXList1);
        jXList1.setModel(le_);
        jXList1.setCellRenderer(new ListRenderer());

        jXList1.addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent e) {
                if (SwingUtilities.isRightMouseButton(e)) {

                    boolean check = false;
                    for (int i = 0; i < jXList1.getVisibleRowCount(); i++) {
                        if (jXList1.getCellBounds(i, i) != null) {
                            if (jXList1.getCellBounds(i, i).contains(e.getPoint())) {
                                check = true;
                            }
                        } else {
                            break;
                        }
                    }
                    if (check) {
                        jXList1.setSelectedIndex(jXList1.locationToIndex(e.getPoint()));
                        PopUpDesktop dv = new PopUpDesktop(jTabbedPane1, ((TableEntreprise)jTable1.getModel()).getEntreprise(), ((ListExercice) jXList1.getModel()).getExercice());
                        dv.show(e.getComponent(), e.getX(), e.getY());
                    }
                }
            }
        });
        ExerciceRequest.getInstance().add_fire_component(le_, jXList1);

        ListSelectionModel listSelectionModel = jTable1.getSelectionModel();
        listSelectionModel.addListSelectionListener(new ListSelectionListenerEntreprise(le_, jTable1));

        jXTaskPane6.add(new EditEntreprise().getContentPane());
        jXTaskPane7.add(new EditExercice().getContentPane());
        jXTaskPane8.add(new EditStructure().getContentPane(), BorderLayout.CENTER);

        addListeners();
        
       // jXTitledPanel2.setTitlePainter(new MattePainter(new Color(255,255,255)));
        
        
        jTable1.setDefaultRenderer(String.class, new TableEntepriseRenderer());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXStatusBar1 = new org.jdesktop.swingx.JXStatusBar();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jXImageView1 = new org.jdesktop.swingx.JXImageView();
        jPanel5 = new javax.swing.JPanel();
        jXTitledPanel2 = new org.jdesktop.swingx.JXTitledPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jXSearchField1 = new org.jdesktop.swingx.JXSearchField();
        jXTitledPanel1 = new org.jdesktop.swingx.JXTitledPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jXList1 = new org.jdesktop.swingx.JXList();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jXTaskPaneContainer3 = new org.jdesktop.swingx.JXTaskPaneContainer();
        jXTaskPane6 = new org.jdesktop.swingx.JXTaskPane();
        jXTaskPane7 = new org.jdesktop.swingx.JXTaskPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jXTaskPaneContainer4 = new org.jdesktop.swingx.JXTaskPaneContainer();
        jXTaskPane8 = new org.jdesktop.swingx.JXTaskPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ComptEdit");
        setMinimumSize(new java.awt.Dimension(977, 537));

        jLabel1.setText("Status");
        jXStatusBar1.add(jLabel1);

        getContentPane().add(jXStatusBar1, java.awt.BorderLayout.SOUTH);

        jTabbedPane1.setBackground(java.awt.Color.lightGray);
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setOpaque(true);

        jPanel1.setBackground(java.awt.Color.darkGray);
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(new java.awt.BorderLayout());

        jXImageView1.setBackgroundPainter(null);
        jXImageView1.setImage(Resizer.get_image("Icon/banniere.png")
        );
        jXImageView1.setOpaque(false);
        jXImageView1.setEditable(false);

        javax.swing.GroupLayout jXImageView1Layout = new javax.swing.GroupLayout(jXImageView1);
        jXImageView1.setLayout(jXImageView1Layout);
        jXImageView1Layout.setHorizontalGroup(
            jXImageView1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1113, Short.MAX_VALUE)
        );
        jXImageView1Layout.setVerticalGroup(
            jXImageView1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 175, Short.MAX_VALUE)
        );

        jPanel4.add(jXImageView1, java.awt.BorderLayout.NORTH);

        jPanel1.add(jPanel4, java.awt.BorderLayout.NORTH);

        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.X_AXIS));

        jXTitledPanel2.setTitle("Liste d'entreprises");

        jTable1.setRowHeight(40);
        jScrollPane2.setViewportView(jTable1);

        jXSearchField1.setBackground(java.awt.Color.lightGray);
        jXSearchField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jXSearchField1.setPromptFontStyle(java.awt.Font.BOLD);
        jXSearchField1.setRecentSearchesSaveKey("");
        jXSearchField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jXSearchField1KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jXTitledPanel2Layout = new javax.swing.GroupLayout(jXTitledPanel2.getContentContainer());
        jXTitledPanel2.getContentContainer().setLayout(jXTitledPanel2Layout);
        jXTitledPanel2Layout.setHorizontalGroup(
            jXTitledPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jXTitledPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jXTitledPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jXSearchField1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE))
                .addContainerGap())
        );
        jXTitledPanel2Layout.setVerticalGroup(
            jXTitledPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jXTitledPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jXSearchField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        jPanel5.add(jXTitledPanel2);

        jXTitledPanel1.setTitle("Liste d'exercices");

        jXList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jXList1.setFocusable(false);
        jScrollPane1.setViewportView(jXList1);

        javax.swing.GroupLayout jXTitledPanel1Layout = new javax.swing.GroupLayout(jXTitledPanel1.getContentContainer());
        jXTitledPanel1.getContentContainer().setLayout(jXTitledPanel1Layout);
        jXTitledPanel1Layout.setHorizontalGroup(
            jXTitledPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXTitledPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
                .addContainerGap())
        );
        jXTitledPanel1Layout.setVerticalGroup(
            jXTitledPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXTitledPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.add(jXTitledPanel1);

        jPanel1.add(jPanel5, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Accueil", Resizer.get_resize_icon("Icon/home.png", 50, 50)
            , jPanel1);

        jPanel2.setBackground(java.awt.Color.lightGray);
        jPanel2.setOpaque(false);

        jXTaskPaneContainer3.setBackground(java.awt.Color.lightGray);

        jXTaskPane6.setBackground(java.awt.Color.lightGray);
        jXTaskPane6.setTitle("Edition des entreprises");
        jXTaskPaneContainer3.add(jXTaskPane6);

        jXTaskPane7.setBackground(java.awt.Color.lightGray);
        jXTaskPane7.setTitle("Edition d'exercice");
        jXTaskPaneContainer3.add(jXTaskPane7);

        jScrollPane4.setViewportView(jXTaskPaneContainer3);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1101, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 711, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Edition générale", Resizer.get_resize_icon("Icon/modification.png", 50, 50)
            , jPanel2);

        jPanel3.setBackground(java.awt.Color.lightGray);
        jPanel3.setOpaque(false);

        jXTaskPaneContainer4.setBackground(java.awt.Color.lightGray);
        jXTaskPaneContainer4.setLayout(new java.awt.BorderLayout());

        jXTaskPane8.setBackground(java.awt.Color.lightGray);
        jXTaskPane8.setTitle("Edition des structures analytiques");
        jXTaskPane8.setOpaque(false);
        jXTaskPane8.getContentPane().setLayout(new java.awt.BorderLayout());
        jXTaskPaneContainer4.add(jXTaskPane8, java.awt.BorderLayout.CENTER);

        jScrollPane5.setViewportView(jXTaskPaneContainer4);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 1101, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 711, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Edition de structure analytique", Resizer.get_resize_icon("Icon/modification_entreprise.png", 50, 50)
            , jPanel3);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Fichier");

        jMenuItem1.setText("Quitter");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edition");

        jMenuItem2.setText("Edition des entreprises");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Edition des structures analytiques");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addListeners() {
        ListSelectionModel cellSelectionModel = jTable1.getSelectionModel();
        cellSelectionModel.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        cellSelectionModel.addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                String selectedData = null;

                int selectedRow = jTable1.getSelectedRow();

            }

        });

    }

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        EditEntreprise mw = new EditEntreprise();
        mw.setLocation(100, 100);
        mw.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jXSearchField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jXSearchField1KeyReleased
        em_.property_change();
    }//GEN-LAST:event_jXSearchField1KeyReleased

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        EditStructure mw = new EditStructure();
        mw.setLocation(100, 100);
        mw.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed


    
    public void addAffectationTab(String title, Entreprise entreprise, Exercice exercice)
    {
        jTabbedPane1.addTab(title, new EditAffectation(entreprise, exercice));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private org.jdesktop.swingx.JXImageView jXImageView1;
    private org.jdesktop.swingx.JXList jXList1;
    private org.jdesktop.swingx.JXSearchField jXSearchField1;
    private org.jdesktop.swingx.JXStatusBar jXStatusBar1;
    private org.jdesktop.swingx.JXTaskPane jXTaskPane6;
    private org.jdesktop.swingx.JXTaskPane jXTaskPane7;
    private org.jdesktop.swingx.JXTaskPane jXTaskPane8;
    private org.jdesktop.swingx.JXTaskPaneContainer jXTaskPaneContainer3;
    private org.jdesktop.swingx.JXTaskPaneContainer jXTaskPaneContainer4;
    private org.jdesktop.swingx.JXTitledPanel jXTitledPanel1;
    private org.jdesktop.swingx.JXTitledPanel jXTitledPanel2;
    // End of variables declaration//GEN-END:variables
    private TableEntreprise em_;
    private ListExercice le_;
}
