/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import DragAndDrop.AffectHandler;
import Renderer.List.ListCompteRenderer;
import comptedit_db.Entreprise;
import comptedit_db.Exercice;
import javax.swing.DefaultListModel;

/**
 *
 * @author Flash
 */
public class EditAffectation extends javax.swing.JPanel {

    /**
     * Creates new form EditAffectation
     */
    private Exercice exercice_;
    private Entreprise entreprise_;

    public EditAffectation(Entreprise entreprise, Exercice exercice) {

        entreprise_ = entreprise;
        exercice_ = exercice;
        
       
        initComponents();
        jXList1.setCellRenderer(new ListCompteRenderer());
        jXTree1.setTransferHandler(new AffectHandler(jXTree1));
        jXTree1.expandAll();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jXList1 = new org.jdesktop.swingx.JXList();
        jScrollPane2 = new javax.swing.JScrollPane();
        jXTree1 = new org.jdesktop.swingx.JXTree();

        setLayout(new java.awt.GridLayout(1, 2));

        jXList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jXList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jXList1.setDragEnabled(true);
        jScrollPane1.setViewportView(jXList1);

        add(jScrollPane1);

        jScrollPane2.setViewportView(jXTree1);

        add(jScrollPane2);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private org.jdesktop.swingx.JXList jXList1;
    private org.jdesktop.swingx.JXTree jXTree1;
    // End of variables declaration//GEN-END:variables
}
