/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Models.Tree.TreeTools;
import Tools.Resizer;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreePath;
import org.jdesktop.swingx.JXTree;

/**
 *
 * @author Flash
 */
public class PopUpCalc extends javax.swing.JPanel {

    private final JXTree t_;
    private final Object[] path_;

    /**
     * Creates new form PopUpLibelle
     */
    public PopUpCalc(JXTree t, Object[] path) {
        initComponents();
        t_ = t;
        path_ = path;

        jXButton1.setIcon(Resizer.get_resize_icon("Icon/Delete-icon.png", 30, 30));
        jXButton3.setIcon(Resizer.get_resize_icon("Icon/move_up.png", 30, 30));
        jXButton4.setIcon(Resizer.get_resize_icon("Icon/move_down.png", 30, 30));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXButton1 = new org.jdesktop.swingx.JXButton();
        jXButton3 = new org.jdesktop.swingx.JXButton();
        jXButton4 = new org.jdesktop.swingx.JXButton();

        setBorder(null);
        org.jdesktop.swingx.HorizontalLayout horizontalLayout2 = new org.jdesktop.swingx.HorizontalLayout();
        horizontalLayout2.setGap(4);
        setLayout(horizontalLayout2);

        jXButton1.setText("Supprimer le calcul");
        jXButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXButton1ActionPerformed(evt);
            }
        });
        add(jXButton1);

        jXButton3.setText("Monter");
        jXButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXButton3ActionPerformed(evt);
            }
        });
        add(jXButton3);

        jXButton4.setText("Descendre");
        jXButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXButton4ActionPerformed(evt);
            }
        });
        add(jXButton4);
    }// </editor-fold>//GEN-END:initComponents

    private void jXButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXButton1ActionPerformed
        TreeTools tools = new TreeTools(t_);

        TreePath path = new TreePath(path_);
        DefaultMutableTreeNode n = (DefaultMutableTreeNode) path.getLastPathComponent();
        DefaultMutableTreeNode parent = (DefaultMutableTreeNode) n.getParent();
        if (path_.length == 3 && !tools.check_calc_for_delete_node(path_)) {
            JOptionPane.showMessageDialog(this,
                    "Impossible de supprimer le compte :" + n.toString() + " car il est attaché à un calcul",
                    "Erreur",
                    JOptionPane.ERROR_MESSAGE);
            return;
        } else {
            parent.remove(n);
        }

        t_.setModel(
                new DefaultTreeModel((DefaultMutableTreeNode) t_.getModel().getRoot()));
        t_.expandAll();


    }//GEN-LAST:event_jXButton1ActionPerformed

    private void jXButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXButton3ActionPerformed
        TreeTools tools = new TreeTools(t_);
        tools.up_item(path_);
    }//GEN-LAST:event_jXButton3ActionPerformed

    private void jXButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXButton4ActionPerformed
        TreeTools tools = new TreeTools(t_);
        tools.down_item(path_);
    }//GEN-LAST:event_jXButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXButton jXButton1;
    private org.jdesktop.swingx.JXButton jXButton3;
    private org.jdesktop.swingx.JXButton jXButton4;
    // End of variables declaration//GEN-END:variables
}
