/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Models.Tree.TreeTools;
import Tools.Resizer;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.Matcher;
import javax.script.ScriptEngine;
import javax.script.ScriptEngineManager;
import javax.script.ScriptException;
import javax.swing.DefaultListModel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import org.jdesktop.swingx.JXTree;

/**
 *
 * @author Flash
 */
public class PopUpSection extends javax.swing.JPanel {

    private final JXTree t_;
    private final DefaultListModel listModel;
    private Object[] path_;

    /**
     * Creates new form PopUpLibelle
     */
    public PopUpSection(JXTree t, Object[] path) {
        initComponents();
        t_ = t;
        path_ = path;
        jXButton1.setIcon(Resizer.get_resize_icon("Icon/add.png", 30, 30));
        jXButton2.setIcon(Resizer.get_resize_icon("Icon/input_validation.png", 30, 30));
        jXButton3.setIcon(Resizer.get_resize_icon("Icon/frame-icon.png", 30, 30));

        listModel = new DefaultListModel();
        TreeTools tt = new TreeTools(t_);

        List<DefaultMutableTreeNode> l = tt.list_all_calc_exclude_root();
        for (DefaultMutableTreeNode aux : l) {
            listModel.addElement(tt.formatNameCalc(aux));
        }
        jList1.setModel(listModel);
        jEditorPane1.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                boolean check = updateStatus();
                jXButton7.setEnabled(!jTextField1.getText().equals("") && check);
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                boolean check = updateStatus();
                jXButton7.setEnabled(!jTextField1.getText().equals("") && check);
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                boolean check = updateStatus();
                jXButton7.setEnabled(!jTextField1.getText().equals("") && check);
            }
        });

    }

    public List<String> listVariablesOf(String str) {
        String token = "";
        List<String> l = new ArrayList<String>();
        for (int i = 0; i < str.length(); i++) {
            if (str.charAt(i) == '$' && token.equals("")) {
                token += "$";
            } else if (str.charAt(i) == '$' && !token.equals("")) {
                l.add(token + "$");
                token = "";
            } else if (!token.equals("")) {
                token += str.charAt(i);
            }
        }
        return l;
    }

    public boolean updateStatus() {
        String exp = jEditorPane1.getText();
        jXButton7.setIcon(Resizer.get_resize_icon("Icon/Delete-icon.png", 30, 30));
        List<String> l_variable = listVariablesOf(exp);
        for (String variable : l_variable) {
            if (listModel.indexOf(variable) == -1) {
                return false;
            }
            exp = exp.replaceFirst(Matcher.quoteReplacement(variable), "0");
        }
        ScriptEngineManager mgr = new ScriptEngineManager();
        ScriptEngine engine = mgr.getEngineByName("JavaScript");
        boolean test = false;
        try {
            System.out.println("Engine : " + engine.eval(exp));
            jXButton7.setIcon(Resizer.get_resize_icon("Icon/ok.png", 30, 30));
            test = true;
        } catch (ScriptException ex) {
        }
        return test;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jXButton1 = new org.jdesktop.swingx.JXButton();
        jXButton3 = new org.jdesktop.swingx.JXButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jXTextField2 = new org.jdesktop.swingx.JXTextField();
        jXButton2 = new org.jdesktop.swingx.JXButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jXPanel3 = new org.jdesktop.swingx.JXPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jXPanel2 = new org.jdesktop.swingx.JXPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jXButton7 = new org.jdesktop.swingx.JXButton();

        setBorder(null);
        setLayout(new java.awt.CardLayout());

        jPanel2.setLayout(new java.awt.BorderLayout());

        jXButton1.setText("Ajouter une section");
        jXButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jXButton1, java.awt.BorderLayout.WEST);

        jXButton3.setText("Ajouter une règle de calcul");
        jXButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jXButton3, java.awt.BorderLayout.CENTER);

        add(jPanel2, "card3");

        jXTextField2.setColumns(20);
        jXTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXTextField2ActionPerformed(evt);
            }
        });
        jXTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jXTextField2KeyReleased(evt);
            }
        });
        jPanel3.add(jXTextField2);

        jXButton2.setEnabled(false);
        jXButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jXButton2);

        jPanel1.add(jPanel3);

        add(jPanel1, "card4");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Ajout Calcul paramétrable :"));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        jPanel7.setLayout(new org.jdesktop.swingx.VerticalLayout());

        jXPanel3.setLayout(new java.awt.BorderLayout());

        jLabel4.setText("Nom du calcul :");
        jLabel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 25));
        jXPanel3.add(jLabel4, java.awt.BorderLayout.WEST);

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        jXPanel3.add(jTextField1, java.awt.BorderLayout.CENTER);

        jPanel7.add(jXPanel3);

        jPanel8.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("Compte disponible :");
        jPanel8.add(jLabel2, java.awt.BorderLayout.WEST);

        jList1.setDragEnabled(true);
        jList1.setLayoutOrientation(javax.swing.JList.HORIZONTAL_WRAP);
        jList1.setVisibleRowCount(2);
        jScrollPane2.setViewportView(jList1);

        jPanel8.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel8);

        jXPanel2.setLayout(new java.awt.BorderLayout());

        jLabel3.setText("Expression = ");
        jLabel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 34));
        jXPanel2.add(jLabel3, java.awt.BorderLayout.WEST);

        jEditorPane1.setDragEnabled(true);
        jEditorPane1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jEditorPane1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jEditorPane1);

        jXPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jXButton7.setIcon(Resizer.get_resize_icon("Icon/Delete-icon.png", 30, 30)
        );
        jXButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXButton7ActionPerformed(evt);
            }
        });
        jXPanel2.add(jXButton7, java.awt.BorderLayout.EAST);

        jPanel7.add(jXPanel2);

        jPanel4.add(jPanel7);

        add(jPanel4, "card5");
    }// </editor-fold>//GEN-END:initComponents

    private void jXButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXButton2ActionPerformed
        TreeTools tools = new TreeTools(t_);
        tools.addSection(jXTextField2.getText());
    }//GEN-LAST:event_jXButton2ActionPerformed

    private void jXButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXButton1ActionPerformed
        CardLayout cards = (CardLayout) getLayout();
        cards.show(this, "card4");
    }//GEN-LAST:event_jXButton1ActionPerformed

    private void jXTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jXTextField2ActionPerformed

    private void jXTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jXTextField2KeyReleased
        jXButton2.setEnabled(!jXTextField2.getText().equals(""));
    }//GEN-LAST:event_jXTextField2KeyReleased

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        jXButton7.setEnabled(!jTextField1.getText().equals("") && updateStatus());
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jEditorPane1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jEditorPane1KeyReleased

    }//GEN-LAST:event_jEditorPane1KeyReleased

    private void jXButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXButton7ActionPerformed
        TreeTools tt = new TreeTools(t_);
        tt.addCalcTo("Calcul : $" + jTextField1.getText() + "$ - Expression : \"" + jEditorPane1.getText() + "\"", path_);
    }//GEN-LAST:event_jXButton7ActionPerformed

    private void jXButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXButton3ActionPerformed
        CardLayout cards = (CardLayout) getLayout();
        cards.show(this, "card5");
    }//GEN-LAST:event_jXButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private org.jdesktop.swingx.JXButton jXButton1;
    private org.jdesktop.swingx.JXButton jXButton2;
    private org.jdesktop.swingx.JXButton jXButton3;
    private org.jdesktop.swingx.JXButton jXButton7;
    private org.jdesktop.swingx.JXPanel jXPanel2;
    private org.jdesktop.swingx.JXPanel jXPanel3;
    private org.jdesktop.swingx.JXTextField jXTextField2;
    // End of variables declaration//GEN-END:variables
}
