/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Models.Table.TableFec;
import Renderer.Table.ShowFECRenderer;
import comptedit_db.Exercice;
import comptedit_db.FecRequest;
import java.util.Date;

/**
 *
 * @author Flash
 */
public class ShowFEC extends javax.swing.JPanel {

    /**
     * Creates new form ShowFEC
     */
    public ShowFEC(final Exercice e) {
        initComponents();

        Thread thr = new Thread(new Runnable() {

            @Override
            public void run() {
                try {
                    final TableFec model = new TableFec(e.getFec(), jXTable1);
                    jXTable1.setModel(model);
                    FecRequest.getInstance().add_fire_component(model, jXTable1);

                } finally {
                }
            }
        });
        thr.start();
        
        
        jXTable1.setDefaultRenderer(Integer.class, new ShowFECRenderer());
        jXTable1.setDefaultRenderer(String.class, new ShowFECRenderer());
        jXTable1.setDefaultRenderer(Date.class, new ShowFECRenderer());
        jXTable1.setDefaultRenderer(Float.class, new ShowFECRenderer());
        jXTable1.setDefaultRenderer(Character.class, new ShowFECRenderer());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jXTable1 = new org.jdesktop.swingx.JXTable();

        setLayout(new java.awt.BorderLayout());

        jXTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jXTable1.setRowHeight(25);
        jScrollPane1.setViewportView(jXTable1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXTable jXTable1;
    // End of variables declaration//GEN-END:variables
}
